# Generated by Django 5.1.6 on 2025-02-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_uploadedfile_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='tag',
            field=models.CharField(default='other', max_length=20),
        ),
    ]
